/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  tutorialSidebar: [
    'intro',

    // =============================
    // CORE STANDARD (PRIMARY LAYER)
    // =============================
    {
      type: 'category',
      label: 'Standard',
      link: { type: 'doc', id: 'standard/index' },
      items: [{ type: 'autogenerated', dirName: 'standard' }],
    },

    {
      type: 'category',
      label: 'Technical',
      link: { type: 'doc', id: 'technical/index' },
      items: [{ type: 'autogenerated', dirName: 'technical' }],
    },

    // =============================
    // MARKET & EXECUTION
    // =============================
    {
      type: 'category',
      label: 'Strategy',
      link: { type: 'doc', id: 'strategy/index' },
      items: [{ type: 'autogenerated', dirName: 'strategy' }],
    },

    {
      type: 'category',
      label: 'Sectors',
      link: { type: 'doc', id: 'sectors/index' },
      items: [{ type: 'autogenerated', dirName: 'sectors' }],
    },

    // =============================
    // LONG-FORM VISION
    // =============================
    {
      type: 'category',
      label: 'Whitepaper',
      link: { type: 'doc', id: 'whitepaper/index' },
      items: [{ type: 'autogenerated', dirName: 'whitepaper' }],
    },

    // =============================
    // GOVERNANCE & LEGAL CONTEXT
    // =============================
    {
      type: 'category',
      label: 'Regulatory',
      link: { type: 'doc', id: 'regulatory/index' },
      items: [{ type: 'autogenerated', dirName: 'regulatory' }],
    },

    {
      type: 'category',
      label: 'Foundation',
      link: { type: 'doc', id: 'foundation/index' },
      items: [{ type: 'autogenerated', dirName: 'foundation' }],
    },
  ],
};

module.exports = sidebars;
